
# Triggers on merge into main
on:
  push:
    branches:
      - main

# 
jobs:
  JS-lint: 
    runs-on: ubuntu-latest
    steps:
      - name: Log a message
        run: echo "Init"




  TEST:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - uses: sibiraj-s/action-eslint@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # optional
          eslint-args: '--ignore-path=.gitignore --quiet'
          extensions: 'js,jsx,ts,tsx'
          annotations: true




  HTML-validation: 
    runs-on: ubuntu-latest
    needs: [JS-lint, TEST]
    steps:
      - name: Log a message
        run: echo "Done!"
