
on:
  push:
    branches:
      - main

jobs:
  JS-lint: 
    runs-on: ubuntu-latest
    steps:
      - name: Log a message
        run: echo "Init"

  TEST: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        uses: stefanoeb/eslint-action@1.0.2


  HTML-validation: 
    runs-on: ubuntu-latest
    needs: JS-lint
    steps:
      - name: Log a message
        run: echo "Done!"
