
on:
  push:
    branches:
      - main

jobs:
  log-message: 
    runs-on: ubuntu-latest
    steps:
      - name: Log a message
        run: echo "eslint.yml"

  log-message-2: 
    runs-on: ubuntu-latest
    needs: log-message
    steps:
      - name: Log a message
        run: echo "Done bby!"


