
on:
  push:
    branches:
      - main

jobs:
  log-message: 
    runs-on: ubuntu-latest
    steps:
      - name: Log a message
        run: echo "This is a log message"

  log-message-2: 
    runs-on: ubuntu-latest
    steps:
      - name: Log a message
        run: echo "2222222222"
  




