
on:
  push:
    branches:
      - main

jobs:
  JS-lint: 
    runs-on: ubuntu-latest
    steps:
      - name: Log a message
        run: echo "Init"

  TEST: 
    runs-on: ubuntu-latest
    needs: JS-lint
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx

  HTML-validation: 
    runs-on: ubuntu-latest
    needs: [JS-lint, TEST]
    steps:
      - name: Log a message
        run: echo "Done!"
